TRUNCATE TABLE weapon_nozzle CASCADE;
TRUNCATE TABLE weapon_sight CASCADE;
TRUNCATE TABLE weapon_handle CASCADE;
TRUNCATE TABLE Weapon_skin CASCADE;
TRUNCATE TABLE Weapon CASCADE;
TRUNCATE TABLE Nozzle CASCADE;
TRUNCATE TABLE Sight CASCADE;
TRUNCATE TABLE Handle CASCADE;
TRUNCATE TABLE operator_weapon CASCADE;
TRUNCATE TABLE operator_gadget CASCADE;
TRUNCATE TABLE Map_stats CASCADE;
TRUNCATE TABLE secondary_gadget CASCADE;
TRUNCATE TABLE Operator_skin CASCADE;
TRUNCATE TABLE Operator CASCADE;
TRUNCATE TABLE Users CASCADE;
TRUNCATE TABLE User_stats CASCADE;
TRUNCATE TABLE Maps CASCADE;

